CREATE TABLE radio_stations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL
);

INSERT INTO radio_stations (name, url) VALUES
('80s Radio Hits','https://stream-037.zeno.fm/05eu8medd3quv?zs=nn3VmkBWSbuGUmPs4VtkyQ'),
('9020 FB FM Purwakarta','https://ssg.streamingmurah.com:8434/stream'),
('Ardan Radio','https://n13.rcs.revma.com/ugpyzu9n5k3vv?rj-ttl=5&rj-tok=AAABmRTF5-IATctJZbz5P1yUMQ'),
('B Radio Bandung','https://n08.rcs.revma.com/9yp8b9pd6k3vv'),
('Bahana Fm','https://s1.cloudmu.id/listen/bahana_fm/stream'),
('Brava FM','https://n08.radiojar.com/5k7t0rq3bnzuv?rj-ttl=5&rj-tok=AAABh-BU0xcApWHXZZl4-zR30Q'),
('Campur sari','https://a8.siar.us/listen/campursari/stream'),
('Cosmopolitan','http://stream.radiojar.com/u7d8heq3bnzuv'),
('Dahlia FM','https://svara-stream.radioddns.net/bandung_dahliafm'),
('Delta FM','https://s1.cloudmu.id/listen/delta_fm/stream'),
('DFM Radio Jakarta','https://i.klikhost.com/9000/stream'),
('Elgangga','https://b.alhastream.com:5140/radio?_ic2=1715794029661'),
('Elshinta','https://stream-ssl.arenastreaming.com:8000/jakarta'),
('Female Radio','https://s1.cloudmu.id/listen/female_radio/stream'),
('Flamboyan FM','https://i.klikhost.com/8236/stream'),
('Gajahmada FM','https://server.radioimeldafm.co.id/radio/8040/gajahmadafm'),
('Gema Surya FM','https://r5.siar.us:9420/mp3.mp3'),
('Gen FM 98.7 Jakarta','https://ic.mari.co.id:8443/genfm'),
('Gen FM Surabaya','https://ic.mari.co.id:8443/gensbyfm'),
('Global Radio Jakarta','https://proxy.rctiplus.com/?name=http://111.119.207.125:8064/;'),
('Hard Rock','https://n08.radiojar.com/7csmg90fuqruv.mp3?rj-tok=AAABh99NlQQAnnz8d1obRSB4IQ&rj-ttl=5'),
('Hits Memories','https://onlineradiobox.com/ping/id.hitsmemories'),
('HOT FM','https://ic.mari.co.id:8443/hotfm'),
('I-Dream Radio','https://void.idserverhost.com:8010/;'),
('Idola fm semarang','https://server.radioidola.com:8880/idolafm'),
('IMI radio','https://a1.siar.us/listen/imiradio/stream'),
('Imelda FM','https://server.radioimeldafm.co.id:8030/imeldafm'),
('iradio Bandung','https://n0d.radiojar.com/u6ppe6hswk8uv?rj-ttl=5&rj-tok=AAABh91unGUAQWkoQMxUWz6UvQ'),
('iradio jakarta','https://n13.radiojar.com/4ywdgup3bnzuv'),
('Jak 101 FM','https://ic.mari.co.id:8443/jakfm'),
('Kajian Islam','https://stream-002.zeno.fm/ge2ekgd7f18uv?zs=Y3dB0G3tQ1WBU2tWIwzIJg'),
('KIS FM Semarang','http://123.255.201.126:8020/kisfm'),
('KISI FM','https://live.kisifm.com/listen/kisifm/kisifm'),
('Kiss FM','https://ic.mari.co.id:8443/kisfm'),
('Loker Musik Indonesia','https://stream.lokermusik.com/listen/lokermusik/lokermusik'),
('Media fm','http://streaming.radiomediafm.com:8400/;stream.nsv'),
('Medan fm','https://live.medanfm.id/medanfm.ogg'),
('Megaswara Bogor','https://server.adyadigitalteknologi.com:8010/1'),
('Merdeka fm','http://streaming.merdekafm.com:8020/;stream.nsv'),
('Mendhut FM','http://c4.siar.us:8790/stream'),
('Mettaswara','https://mettaswara.com:8700/indo'),
('Mettaswara Dangdut','https://mettaswara.com:8700/d4d'),
('MGT FM','https://s1.gntr.net/listen/mgtradio/mgtradio'),
('Motion Radio Jakarta','https://cast3.asurahosting.com/proxy/radios22/stream'),
('Most FM','https://ic.mari.co.id:8443/mostfm'),
('MQFM Bandung','https://mqfmstreaming.kamil.web.id/;'),
('Muara dss','https://ssg.streamingmurah.com:8668/;?1683089782130'),
('OZ Bandung','https://streaming.ozradio.id:8443/ozbandung'),
('Paramuda FM','https://i.klikhost.com/8332/;'),
('PASS FM Bandung','https://stream-174.zeno.fm/w70fp14bs18uv'),
('Pop FM','https://i.klikhost.com/8272/stream'),
('Prambors FM','https://s2.cloudmu.id/listen/prambors/stream'),
('Radio BOSS FM','https://a7.siar.us/listen/radiobossfm/stream'),
('Radio Budi Luhur','https://onlineradiobox.com/ping/id.budiluhur'),
('Radio Cakra Bandung','https://stream-156.zeno.fm/yoengdcdzyauv'),
('Radio CBB','https://stream01-ssl.arenastreaming.com:8056/live'),
('Radio CMN','https://stream.coolkas.com/radio/8160/radiocmn'),
('Radio Cosmo','http://scg.streamingmurah.com:8074/stream'),
('Radio Dangdut Indonesia','https://stream.roov.id:8062/stream'),
('Radio Galuh','https://stream.yaomiakba.com/galuhfm'),
('Radio Idola Semarang','https://stream.radioidola.com/listen/idolafm/live'),
('Radio Muara','http://45.64.97.82:8778/;'),
('Radio Musik Indonesia','https://stream-034.zeno.fm/727gv3qrt5quv?zs=q5wF9_yCQgy8tFIM3phRmg'),
('Radio Rodja','https://radioislamindonesia.com/rodja-low.mp3'),
('Raka FM','https://cast2.my-control-panel.com/proxy/radioso5/stream'),
('Rama FM Bandung','https://i.klikhost.com/8330/;'),
('RAS FM','https://i.klikhost.com/9006/stream/1/'),
('RRI Pro 1 Jakarta','https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro1.mp3'),
('RRI Pro 2 Jakarta','https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro2.mp3'),
('RRI Pro 3 Yogyakarta','https://stream-node0.rri.co.id/streaming/14/9014/kbrn.mp3'),
('RRI Pro 4 Jakarta','https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro4.mp3'),
('Simfoni FM','http://i.klikhost.com:9160/;rojer.mp3'),
('Smart FM Jakarta','https://cast2.my-control-panel.com/proxy/radioso3/stream'),
('Smooth FM Jakarta','https://svara-stream.radioddns.net/jakarta_smoothfm_mp3'),
('Sonora FM Jakarta','https://cast1.my-control-panel.com/proxy/radioso1/live'),
('Suara Giri FM','http://streaming.girifm.com:8010/;'),
('Suara Soneta Radio','https://a2.siar.us/listen/suarasoneta/radio.mp3'),
('Suara surabaya','https://c5.siar.us:8000/stream'),
('Sunda Radio','https://sundaradio.com/live/sundaradio'),
('Swara semarang','https://server.radioimeldafm.co.id/radio/8010/swarasemarang'),
('Tangerang radio','https://rl.tangerank.my.id/swara'),
('Trax FM','https://n0a.radiojar.com/rrqf78p3bnzuv?rj-ttl=5&rj-tok=AAABh9163ogAt_w8aT7VUcRuAA'),
('Trijaya FM Jakarta','http://202.147.199.101:8000/;'),
('Urban FM Bandung','https://a1.siar.us/listen/urbanradio/stream'),
('Wijaya FM','http://wijayafm.onlivestreaming.net:9880/stream?'),
('Z 99.9 FM','https://svara-stream.radioddns.net/jakarta_z999fm_aac');
